### PR TITLE
Adding Workflow, sorry for clutter of other PR's

### PR DESCRIPTION
**Pull request by JulianStiebler**
Didn't wanted to bother with test-branches and the commit-action somehow offered a link to pull-request, and i thought it will pull-request to my fork but it did to here.  

- Added workflow to lint over Code for formatting on PullRequests and Push
- Choose if you like Ruff or Black more or just remove em, i thought to just throw em in cause why not

- Added workflow to auto-build exe on push-actions (which should result from a PR-merge aswell)
 - otherwise added possibilty to dispatch it manually under actions
 - it will build everything related to "src/main.py" in one-file, place it under compiled/editor/offlineEditor.exe - upload the Artifact and commit changes aswell as sign it off and merge it automatically

### CODE REVIEW

**Comment by JulianStiebler** [comment]
Somehow the .exe is faulty tho, need to investiagte.

**Comment by JulianStiebler** [comment]
It still produces faulty .exes and im out of knowledge. Tryed 5hrs :'D

Asked here;
https://stackoverflow.com/questions/78534220/github-actions-pyinstaller-builds-broken-exe

**Comment by claudiunderthehood** [comment]
> It still produces faulty .exes and im out of knowledge. Tryed 5hrs :'D
> 
> 
> 
> Asked here;
> 
> https://stackoverflow.com/questions/78534220/github-actions-pyinstaller-builds-broken-exe

That's really weird, don't worry though, try to rest a little, I'll try to have a look at that when u can sit down. You did a tremendous jobs, sometimes it's always the the little things we miss that can cause the damage, we'll find it don't worry!

**Comment by JulianStiebler** [comment]
Workflows are annoying as hell tho, They stop working with one wrong indent too :'D I hate setting them up but it's always a joy to learn anyway. And i aswell you can probably reuse that .yaml very well.

Now the .exe compiles correctly and works under windows, i did include a requirements.txt tho which seemed to solve the issue, despite i also didnt needed any requirements on my local venv.

**Pull request merged**
