### PR TITLE
Update rogueClass.py to fix single starter edit

### PR DESCRIPTION
**Pull request by prephalia**
Resolving Issue #4

### CODE REVIEW

**Comment by prephalia** [comment]
I haven't compiled it but it seems a simple fix anyway. I'd compile, fork and do more stuff if i had access to my main account but i dont wan't to kick it out of GitHub Desktop x')

**Comment by claudiunderthehood** [comment]
> I haven't compiled it but it seems a simple fix anyway. I'd compile, fork and do more stuff if i had access to my main account but i dont wan't to kick it out of GitHub Desktop x')

Thank you so much I must have missed it somehow and pasted iv instead of i hahahah

**Comment by prephalia** [comment]
Comment after merge: I tryed and editing single starters now works correctly. 

Currently it is not build as i dont know if you have a build script or how you configured your build-tool. But the code works, just need to incorporate it under compiled. When my main github account gets back i'll add some styling to the Encrypt/Decrypt Tool to make it more user-friendly.

**Comment by claudiunderthehood** [comment]
> you have a build script or how you configured your 

Yeah I'll edit the compiled version later since I'm not home. 

I'd love for you to improve the html. Sadly I'm very very very bad at graphics, ui and front end in general, so if you'd want to help me with that I'd be so glad. Having to work with both the online version and the offline version plus all the other university stuff, a helping hand would really be nice

**Pull request merged**
